version: "3.9"

services:

  # Exclude when deployed
  sqs:
    image: softwaremill/elasticmq-native
    volumes:
      - ./elasticmq/elasticmq.conf:/opt/elasticmq.conf
    restart: always
    ports:
      - "9324:9324"
      - "9325:9325"

  web:
    build: ./web/ # Exclude when deployed
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - QUEUE_BASE_URL
      - QUEUE_FULL_URL
    depends_on: # Exclude when deployed (SQS should always be up!)
      - "sqs"