version: "3.9"

services:
  sqs:
    image: softwaremill/elasticmq-native
    volumes:
      - ./elasticmq/elasticmq.conf:/opt/elasticmq.conf
    restart: always
    ports:
      - "9324:9324"
      - "9325:9325"

  web:
    build: ./web/
    restart: on-failure
    # ports:
    #   - "80:80"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    depends_on:
      - "sqs"